isClusterService: false
serviceType: NodePort
service:
  externalIPs: ["192.168.56.10"] # Binds to your Hub's private IP

servers:
- zones:
  - zone: homelab.
  port: 53
  plugins:
  - name: log
  - name: errors
  - name: health
  - name: ready
  # This allows External-DNS to push updates via RFC2136
  - name: etcd
    zones:
    - homelab.
    endpoint: "http://etcd-cluster:2379" # Or use the 'file' plugin with 'auto'