provider: coredns
env:
  - name: ETCD_URLS
    value: "http://etcd-cluster:2379"

extraArgs:
  - --source=ingress
  - --domain-filter=homelab
  - --registry=txt
  - --txt-owner-id=microk8s-hub
  # Force all records to point to the Hub IP regardless of internal K8s IPs
  - --target-net-filter=192.168.56.10/32 

policy: sync # This will create AND delete records automatically